# FastAPI Backend
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: unless-stopped
    environment:
      SECRET_KEY: your-secret-key-change-in-production
      CORS_ORIGINS: http://localhost:3000,http://frontend:3000,http://localhost:7000
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      #depends_on:
      #db:
      #  condition: service_healthy
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
